// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:spotifly/shared/data/models/hive_song.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveSongAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveSongAdapter());
  }
}
