import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class YoutubeUserAgent {
  // ytClient and user agent must be matching to get the audio stream
  // Other wise the signed audio stream url generated by youtube_explode_dart using this ytClient will
  // will not work if the user agent used in AudioPlayer/ File Downloader etc.. is not matching
  // i.e Youtube Server must feel both requests are from same place

  static const String userAgent =
      'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36';
  static YoutubeApiClient ytClient = YoutubeApiClient.androidVr;
}
